language: julia
os:
  - osx
  - linux
julia:
  - 0.6
  - 0.7
notifications:
  email: false
addons:
  apt:
    packages:
    - hdf5-tools
before_script:
    - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; brew link --overwrite gcc; brew install hdf5; fi
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd()); Pkg.build("Anasol"); Pkg.test("Anasol"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("Anasol")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
